"""Assembly specifications for furniture construction.

Detailed rules for joint types, fastener patterns, adhesive usage,
pre-drilling, and mounting techniques. Dimensions in mm unless noted.
"""

ASSEMBLY_SPECS: dict = {
    "panel_to_panel": {
        "name": "Unión panel a panel (lateral-piso, lateral-techo, etc.)",
        "methods": [
            {
                "id": "confirmat_only",
                "name": "Solo confirmat",
                "when": "Uniones estándar donde la resistencia del confirmat es suficiente",
                "fastener": "confirmat_7x50",
                "pilot_hole_mm": 5,
                "pilot_depth_mm": 40,
                "min_from_edge_mm": 50,
                "spacing_mm": {"min": 100, "max": 250, "recommended": 200},
                "quantity_rules": [
                    {"panel_length_max_cm": 40, "min_qty": 2},
                    {"panel_length_max_cm": 60, "min_qty": 3},
                    {"panel_length_max_cm": 90, "min_qty": 4},
                    {"panel_length_max_cm": 120, "min_qty": 5},
                ],
                "tightening": "Apretar firme pero sin exceso. Melamina se desgarra si se pasa de torque.",
                "sequence": "Fijar primero los extremos, luego los intermedios.",
            },
            {
                "id": "confirmat_plus_dowel",
                "name": "Confirmat + tarugos de alineación",
                "when": "Uniones largas (>60cm) o que requieren alineación precisa",
                "fastener": "confirmat_7x50",
                "dowel": "wooden_dowel_8x35",
                "dowel_hole_mm": 8,
                "dowel_hole_depth_mm": 18,
                "dowel_spacing_mm": 200,
                "adhesive": "PVA (cola blanca) en los tarugos — NO en el confirmat",
                "process": [
                    "Perforar agujeros de tarugos (8mm, 18mm prof.) en ambos paneles",
                    "Aplicar cola blanca dentro del agujero del tarugo",
                    "Insertar tarugos en un panel",
                    "Unir paneles alineando tarugos",
                    "Perforar piloto de confirmat (5mm) a través de la unión",
                    "Atornillar confirmats",
                    "Limpiar exceso de cola con trapo húmedo antes de que seque",
                ],
            },
            {
                "id": "minifix",
                "name": "Minifix (excéntrica) — unión invisible y desmontable",
                "when": "Muebles que se van a transportar desarmados o exhibición",
                "cam_hole_mm": 15,
                "cam_hole_depth_mm": 12.5,
                "bolt_hole_mm": 8,
                "bolt_hole_depth_mm": 34,
                "cam_distance_from_edge_mm": 34,
                "process": [
                    "Perforar orificio de excéntrica (15mm, 12.5mm prof.) en panel receptor",
                    "Perforar orificio de perno (8mm, 34mm prof.) en panel lateral",
                    "Atornillar perno en panel lateral",
                    "Insertar perno en orificio de excéntrica",
                    "Girar excéntrica 180° con destornillador para trabar",
                ],
            },
        ],
        "by_joint_type": {
            "side_to_bottom": {
                "description": "Lateral a piso — carga vertical directa",
                "recommended": "confirmat_plus_dowel",
                "min_confirmats": 3,
                "note": "El piso va ENTRE los laterales, no encima. Así la carga se transfiere directo al lateral.",
            },
            "side_to_top": {
                "description": "Lateral a techo/tapa",
                "recommended": "confirmat_only",
                "min_confirmats": 3,
                "note": "Menos carga que el piso. Confirmat solo es suficiente.",
            },
            "side_to_rail": {
                "description": "Lateral a travesaño",
                "recommended": "confirmat_only",
                "min_confirmats": 2,
                "note": "Los travesaños son de 8-10cm de alto. 2 confirmats son suficientes.",
            },
            "side_to_divider": {
                "description": "Piso/techo a división vertical",
                "recommended": "confirmat_plus_dowel",
                "min_confirmats": 2,
                "note": "La división vertical porta carga de repisas. Reforzar con tarugos.",
            },
            "shelf_fixed": {
                "description": "Repisa fija a lateral",
                "recommended": "confirmat_only",
                "min_confirmats": 2,
                "note": "2 confirmats por lado. No usar pegamento por si necesita ajuste futuro.",
            },
        },
    },
    "back_panel": {
        "name": "Instalación de respaldo (panel trasero)",
        "methods": [
            {
                "id": "nailed",
                "name": "Clavado por detrás",
                "when": "Método estándar para MDF 3mm. Rápido y efectivo.",
                "material": "MDF 3mm (mínimo), 6mm (recomendado para muebles grandes)",
                "fastener": "Clavos de 1\" (25mm) o grapas de 20mm",
                "spacing_mm": 150,
                "from_edge_mm": 15,
                "adhesive": "Opcional: línea de cola blanca en el canto trasero de cada panel antes de clavar. Mejora rigidez.",
                "process": [
                    "Verificar que el mueble esté a escuadra midiendo diagonales (diferencia < 2mm)",
                    "Cortar respaldo 2mm menor que la abertura total (holgura de ajuste)",
                    "Aplicar línea de cola en cantos traseros (opcional pero recomendado)",
                    "Posicionar respaldo alineando con un borde",
                    "Clavar una esquina y verificar escuadra",
                    "Clavar esquina opuesta en diagonal",
                    "Completar perimetral cada 15cm",
                    "El respaldo cuadra el mueble — no omitir este paso",
                ],
            },
            {
                "id": "grooved",
                "name": "Embutido en canal (ranura)",
                "when": "Acabado más limpio. El respaldo queda oculto.",
                "material": "MDF 3mm",
                "groove_width_mm": 4,
                "groove_depth_mm": 8,
                "groove_from_back_edge_mm": 10,
                "adhesive": "Cola blanca en la ranura antes de insertar",
                "process": [
                    "Fresar canal de 4mm x 8mm a 10mm del borde trasero en todos los paneles perimetrales",
                    "IMPORTANTE: fresar ANTES de ensamblar el mueble",
                    "El respaldo se desliza en la ranura durante el ensamble",
                    "Aplicar cola en la ranura para fijación permanente",
                ],
                "note": "Requiere fresadora o CNC. No apto para fabricación manual básica.",
            },
        ],
    },
    "hinge_mounting": {
        "name": "Montaje de bisagras de cazoleta 35mm",
        "cup_diameter_mm": 35,
        "cup_depth_mm": 12,
        "cup_center_from_edge_mm": 22,
        "hinge_plate_screws": "Tornillos 3.5x16mm (incluidos con bisagra)",
        "placement": {
            "from_top_mm": 100,
            "from_bottom_mm": 100,
            "intermediate_spacing_mm": {"min": 400, "max": 500},
        },
        "quantity_by_door_height": [
            {"max_height_cm": 60, "qty": 2},
            {"max_height_cm": 120, "qty": 3},
            {"max_height_cm": 180, "qty": 4},
            {"max_height_cm": 240, "qty": 5},
        ],
        "process": [
            "Marcar posición de la cazoleta: 22mm del borde de la puerta (centro)",
            "Perforar con broca Forstner de 35mm a 12mm de profundidad",
            "CUIDADO: no perforar de más — la puerta solo tiene 16-18mm",
            "Insertar bisagra en la cazoleta y fijar con tornillos a la puerta",
            "Atornillar placa de montaje al lateral del mueble",
            "Colgar puerta enganchando bisagra en placa",
            "Ajustar en 3 ejes: profundidad, lateral, vertical",
        ],
        "adjustment": {
            "depth": "Tornillo trasero — acerca/aleja la puerta del mueble",
            "lateral": "Tornillo frontal — mueve la puerta izquierda/derecha",
            "vertical": "Tornillos de placa — sube/baja la puerta",
        },
        "overlay_types": {
            "full": "Puerta cubre todo el lateral (estándar)",
            "half": "Puerta cubre medio lateral — para puertas que comparten lateral",
            "inset": "Puerta queda al ras dentro del marco — más preciso, más difícil",
        },
    },
    "drawer_slide_mounting": {
        "name": "Montaje de correderas telescópicas",
        "clearance_per_side_mm": 12.7,
        "total_clearance_mm": 25.4,
        "slide_screws": "Tornillos 3.5x16mm",
        "process": [
            "Calcular ancho del cajón: ancho del hueco - 25.4mm (12.7mm por lado)",
            "Separar la corredera en dos partes: riel del mueble y riel del cajón",
            "Marcar línea horizontal en el lateral interno del mueble",
            "Atornillar riel del mueble al lateral — usar agujeros ovalados primero para ajuste",
            "Atornillar riel del cajón al costado del cajón (centrado en altura)",
            "Insertar cajón alineando rieles",
            "Verificar que el cajón corra suave y cierre parejo",
            "Fijar con tornillos en agujeros redondos (definitivos)",
        ],
        "common_mistakes": [
            "Cajón demasiado ancho — no entra o roza. Siempre descontar 25.4mm.",
            "Rieles no paralelos — el cajón se traba. Usar nivel.",
            "Tornillos demasiado largos — sobresalen al interior del mueble.",
        ],
    },
    "shelf_pins": {
        "name": "Instalación de soportes de repisa (sistema 32mm)",
        "hole_diameter_mm": 5,
        "hole_depth_mm": 10,
        "vertical_spacing_mm": 32,
        "from_front_mm": 30,
        "from_back_mm": 30,
        "pins_per_shelf": 4,
        "process": [
            "Marcar columna de agujeros a 30mm del borde frontal y 30mm del borde trasero",
            "Espaciar agujeros cada 32mm en vertical (sistema 32mm europeo)",
            "Perforar con broca de 5mm a exactamente 10mm de profundidad",
            "TIP: usar tope de profundidad en el taladro o cinta adhesiva como marca",
            "Insertar 4 pernos (2 por lateral) a la altura deseada",
            "Apoyar repisa sobre los pernos",
        ],
        "jig_recommendation": "Usar plantilla de perforación (jig) para consistencia. Se puede hacer con un trozo de MDF con agujeros cada 32mm.",
    },
    "adhesive_guide": {
        "name": "Guía de adhesivos",
        "types": [
            {
                "id": "pva_white",
                "name": "Cola blanca (PVA)",
                "cure_time_minutes": 30,
                "full_strength_hours": 24,
                "usage": [
                    "Tarugos de madera — siempre",
                    "Respaldo clavado — opcional, mejora rigidez",
                    "Respaldo en ranura — siempre",
                    "Refuerzos de listón — siempre",
                    "Uniones de madera maciza — siempre",
                ],
                "NOT_for": [
                    "Uniones con confirmat — el tornillo ya da suficiente agarre y el pegamento impide desarmar",
                    "Repisas ajustables — deben poder removerse",
                    "Uniones con minifix — están diseñadas para ser desmontables",
                ],
                "tips": [
                    "Aplicar línea fina, no exceso — el exceso mancha y no agrega resistencia",
                    "Limpiar exceso inmediatamente con trapo húmedo",
                    "Prensar o clampear durante mínimo 30 minutos",
                    "Temperatura ambiente > 10°C para curado correcto",
                ],
            },
            {
                "id": "contact_cement",
                "name": "Cemento de contacto",
                "usage": [
                    "Laminado HPL sobre MDF/aglomerado",
                    "Chapas de madera sobre MDF",
                ],
                "NOT_for": [
                    "Uniones estructurales — no tiene resistencia mecánica",
                    "Paneles de melamina — la melamina no absorbe adhesivo",
                ],
            },
            {
                "id": "polyurethane",
                "name": "Pegamento de poliuretano (PU)",
                "cure_time_hours": 4,
                "full_strength_hours": 24,
                "usage": [
                    "Uniones que estarán expuestas a humedad (baños)",
                    "Madera maciza a madera maciza (alternativa a PVA para exterior)",
                ],
                "tips": [
                    "Expande al curar — no usar en exceso",
                    "Humedecer una superficie antes de aplicar para mejor agarre",
                ],
            },
        ],
    },
    "pre_drilling": {
        "name": "Guía de pre-taladrado por material",
        "rules": [
            {
                "material": "melamine_16",
                "confirmat_pilot_mm": 5,
                "confirmat_pilot_depth_mm": 40,
                "dowel_pilot_mm": 8,
                "dowel_pilot_depth_mm": 18,
                "hinge_cup_mm": 35,
                "hinge_cup_depth_mm": 12,
                "shelf_pin_mm": 5,
                "shelf_pin_depth_mm": 10,
                "notes": "SIEMPRE pre-taladrar. La melamina se fisura sin piloto.",
            },
            {
                "material": "melamine_18",
                "confirmat_pilot_mm": 5,
                "confirmat_pilot_depth_mm": 45,
                "dowel_pilot_mm": 8,
                "dowel_pilot_depth_mm": 20,
                "hinge_cup_mm": 35,
                "hinge_cup_depth_mm": 13,
                "shelf_pin_mm": 5,
                "shelf_pin_depth_mm": 10,
                "notes": "Mismo proceso que 16mm, pilotos un poco más profundos.",
            },
            {
                "material": "mdf_15",
                "confirmat_pilot_mm": 5,
                "confirmat_pilot_depth_mm": 38,
                "dowel_pilot_mm": 8,
                "dowel_pilot_depth_mm": 17,
                "hinge_cup_mm": 35,
                "hinge_cup_depth_mm": 11,
                "shelf_pin_mm": 5,
                "shelf_pin_depth_mm": 10,
                "notes": "MDF se perfora fácil pero el agarre es menor. Considerar tarugos + cola.",
            },
            {
                "material": "mdf_18",
                "confirmat_pilot_mm": 5,
                "confirmat_pilot_depth_mm": 42,
                "dowel_pilot_mm": 8,
                "dowel_pilot_depth_mm": 19,
                "hinge_cup_mm": 35,
                "hinge_cup_depth_mm": 13,
                "shelf_pin_mm": 5,
                "shelf_pin_depth_mm": 10,
                "notes": "Mejor agarre que MDF 15. Aún así usar tarugos en uniones de carga.",
            },
            {
                "material": "plywood_18",
                "confirmat_pilot_mm": 5,
                "confirmat_pilot_depth_mm": 42,
                "dowel_pilot_mm": 8,
                "dowel_pilot_depth_mm": 19,
                "hinge_cup_mm": 35,
                "hinge_cup_depth_mm": 13,
                "shelf_pin_mm": 5,
                "shelf_pin_depth_mm": 10,
                "notes": "Excelente agarre de tornillo. Pre-taladrar igual para evitar astillado en cara.",
            },
            {
                "material": "solid_pine_20",
                "confirmat_pilot_mm": 4,
                "confirmat_pilot_depth_mm": 45,
                "dowel_pilot_mm": 8,
                "dowel_pilot_depth_mm": 20,
                "hinge_cup_mm": 35,
                "hinge_cup_depth_mm": 14,
                "shelf_pin_mm": 5,
                "shelf_pin_depth_mm": 12,
                "notes": "Piloto de confirmat puede ser 4mm (madera agarra mejor). Pre-taladrar siempre para evitar rajaduras.",
            },
        ],
    },
}
